services:
  - type: web
    name: billflow-backend
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/billing-backend-1.0.0.jar
    port: 8080
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.cvcdttopbtuzhhjkwaeh.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: TsrifEnoTwo4321$